config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tracking_gems

  resources :unread_gems

  resources :ignoring_gems
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/execution_history.rb
class ExecutionHistory < ApplicationRecord
end

app/models/ignoring_gem.rb
class IgnoringGem < ApplicationRecord
end

app/models/ruby_gem.rb
class RubyGem
  attr_reader :name, :version, :description, :url

  def initialize(name, version, description, url)
    @name = name
    @version = version
    @description = description
    @url = url
  end

  def ==(other_object)
    return false unless other_object
    return false if @name.nil? || other_object.name.nil?

    @name == other_object.name
  end

  class << self
    def client
      @client
    end

    def client=(client)
      @client = client
    end

    def collect_gems(since_id)
      ruby_gems_tweets = fetch_user_timeline(since_id)

      # TODO description 内の短縮 URL を展開する
      ruby_gems = ruby_gems_tweets.each_with_object([]) {|tweet, gems|
        if /\A(?<gem_name>.+) \((?<gem_version>.+)\): (?<gem_description>.+) https:\/\/t.co/ =~ tweet.full_text
          gem_url = tweet.uris.find {|uri| uri.display_url.start_with?('rubygems.org') }.try(:expanded_url).try(:to_s)
          gem = RubyGem.new(gem_name, gem_version, gem_description, gem_url)

          gems << gem unless gems.include?(gem)
        end
      }

      yield ruby_gems, ruby_gems_tweets.first.id
    end

    def fetch_user_timeline(since_id)
      client.timeline_with_paging(since_id) {|opt|
        client.user_timeline('rubygems', opt)
      }
    end
  end
end

app/models/tracking_gem.rb
class TrackingGem < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/unread_gem.rb
class UnreadGem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ignoring_gems_controller.rb
class IgnoringGemsController < ApplicationController
  def create
    ignoring_gem = IgnoringGem.new(params.require(:ignoring_gem).permit(:name, :registered_version))

    ignoring_gem.save!

    redirect_to unread_gems_path
  end
end

app/controllers/tracking_gems_controller.rb
class TrackingGemsController < ApplicationController
  def create
    unread_gem = UnreadGem.find(params[:unread_gem_id])
    tracking_gem = TrackingGem.new(name: unread_gem.name, latest_version: unread_gem.version, source_url: params[:source_url])
    tracking_gem.save!

    redirect_to unread_gems_path
  end
end

app/controllers/unread_gems_controller.rb
class UnreadGemsController < ApplicationController
  before_action :load_resource

  def index
  end

  def load_resource
    @unread_gems = UnreadGem.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      GemsTracker
    %meta{'http-equiv' => 'Content-Type', content: 'text/html; charset=UTF-8'}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = yield

app/views/unread_gems/index.html.haml
- @unread_gems.each do |gem|
  .box
    = gem.name
    = gem.version
    = gem.description
    = link_to 'rubygems', gem.url
    .content
      = form_tag tracking_gems_url do
        = hidden_field_tag :unread_gem_id, gem.id
        = text_field_tag :source_url, nil, class: 'input', placeholder: 'ex) github url'
        = button_tag 'do track', class: 'button is-primary is-outlined'
      = form_for IgnoringGem.new do |f|
        = f.hidden_field :name, value: gem.name
        = f.hidden_field :registered_version, value: gem.version
        = f.button 'ignore', class: 'button is-dark'